package construction

import squants.mass._
import squants.space.Length
import squants.energy.Megawatts
import squants.energy.Power
import squants.energy.Energy

/**
 * Transmission of the energy generated by a wind farm to the grid
 *
 * Different types of cables are used :
 *
 * 33 kV HVAC cables used internally in offshore wind farms
 * 132 kV HVAC cables used to transmit power from a wind farm to the grid onshore and
 * 450 kV HVDC cables used for long-distance power transmission between for instance countries
 *
 * From : Assessing the Life Cycle Environmental Impacts of Offshore 
 * Wind Power Generation and Power Transmission in the North Sea - Christine Birkeland
 * 
 * &&
 * 
 * Life cycle assessment of electricity produced from onshore sited wind power plants based on Vestas V82-1.65 MW turbines
 * 
 * &&
 * 
 * Life cycle assessment of Electricity production from a V90-2MW Gridstream Wind Plant (Vestas)
 * 
 * &&
 * 
 * Life cycle assessment of offshore and onshore sited wind power plants based Date: 2005-03-29 on Vestas V90-3.0 MW turbines
 */

object Transmission {

  //internally in wind farms = composition / km
  val internalOffshoreCables = Components(
    (Tonnes(7.82), Lead),
    (Tonnes(6.13), Copper),
    (Tonnes(1.82), Polyethylene),
    (Tonnes(11.87), Steel),
    (Tonnes(1.22), Polypropylene))

  // from a wind farm to the grid onshore, quantity = composition / km
  val toOnshoreGridCables = Components(
    (Tonnes(22), Lead),
    (Tonnes(28), Copper),
    (Tonnes(7), Polyethylene),
    (Tonnes(28), Steel),
    (Tonnes(4), Polypropylene))

  def toOnshoreGridCablesEnergy(distance: Length) : Energy = {
    toOnshoreGridCables.embodiedEnergy * distance.toKilometers
  }

  // Scale this with the size of the wind farm, here it is given for 300 MW
  val refPower = Megawatts(300)
  val transformerStation = Components(
    (Tonnes(91.8), Steel),
    (Tonnes(24), Copper))
    
  val internalOnshoreCables = Components(
    (Tonnes(63.4), Aluminium),
    (Tonnes(55.2), Plastic),
    (Tonnes(30.9), Copper))
  val externalOnshoreCables = Components(
    (Tonnes(1519), Plastic),
    (Tonnes(953), Aluminium),
    (Tonnes(238.6), Copper))

  def transformerStation(power: Power): Components = transformerStation * (power / refPower)
  def internalOnshoreCables(power: Power): Components = internalOnshoreCables * (power / refPower)
  def externalOnshoreCables(power: Power): Components = externalOnshoreCables * (power / refPower)

}

