package construction

import squants.mass._
import squants.space.Length
import squants.energy.Megawatts
import squants.energy.Power

/**
 * Transmission of the energy generated by a wind farm to the grid
 *
 * Different types of cables are used :
 *
 * 33 kV HVAC cables used internally in offshore wind farms
 * 132 kV HVAC cables used to transmit power from a wind farm to the grid onshore and
 * 450 kV HVDC cables used for long-distance power transmission between for instance countries
 *
 */

object Transmission {

  val internalOffshoreCables = Components(
    (Tonnes(7.82), Lead),
    (Tonnes(6.13), Copper),
    (Tonnes(1.82), Polyethylene),
    (Tonnes(11.87), Steel),
    (Tonnes(1.22), Polypropylene))

  val toOnshoreGridCables = Components(
    (Tonnes(22), Lead),
    (Tonnes(28), Copper),
    (Tonnes(7), Polyethylene),
    (Tonnes(28), Steel),
    (Tonnes(4), Polypropylene))

  def toOnshoreGridCablesEnergy(distance: Length) {
    toOnshoreGridCables.embodiedEnergy * distance.toKilometers
  }

  // Scale this with the size of the wind farm, here it is given for 300 MW
  val refPower = Megawatts(300)
  val substation = Components(
    (Tonnes(91.8), Steel),
    (Tonnes(24), Copper))
  val internalOnshoreCables = Components(
    (Tonnes(63.4), Aluminium),
    (Tonnes(55.2), Plastic),
    (Tonnes(30.9), Copper))
  val externalOnshoreCables = Components(
    (Tonnes(1519), Plastic),
    (Tonnes(953), Aluminium),
    (Tonnes(238.6), Copper))

  def substation(power: Power): Components = substation * (power / refPower)
  def internalOnshoreCables(power: Power): Components = internalOnshoreCables * (power / refPower)
  def externalOnshoreCables(power: Power): Components = externalOnshoreCables * (power / refPower)

}

