package construction

import squants.mass._
import squants.space._
import squants.energy._
import squants.time._

/**
 * Transmission of the energy generated by a wind farm to the grid
 *
 * Different types of cables are used :
 *
 * 33 kV HVAC cables used internally in offshore wind farms
 * 132 kV HVAC cables used to transmit power from a wind farm to the grid onshore and
 * 450 kV HVDC cables used for long-distance power transmission between for instance countries
 *
 * From : Assessing the Life Cycle Environmental Impacts of Offshore
 * Wind Power Generation and Power Transmission in the North Sea - Christine Birkeland
 *
 * &&
 *
 * Life cycle assessment of electricity produced from onshore sited wind power plants based on Vestas V82-1.65 MW turbines
 *
 * &&
 *
 * Life cycle assessment of Electricity production from a V90-2MW Gridstream Wind Plant (Vestas)
 *
 * &&
 *
 * Life cycle assessment of offshore and onshore sited wind power plants based Date: 2005-03-29 on Vestas V90-3.0 MW turbines
 */
class Cable(referenceCapacity: Power, components: Components,
    installationEnergy: Energy, OMEnergy: Energy, EOLEnergy: Energy, lifeTime: Time) {
  def embodiedEnergy(capacity: Power, distanceToShore: Length): Energy = {
    println(capacity / referenceCapacity)
    (installationEnergy + OMEnergy + EOLEnergy + components.embodiedEnergy * distanceToShore.toKilometers) * (capacity / referenceCapacity)
  }
}

object Transmission {

  // --- OFFSHORE ---
  /**
   * Life cycle assessment of an offshore grid interconnection wind farms and customers across the North Sea
   *
   * Arvesen et al., 2014
   *
   */
  // Components/600 MW Wind Farm
  val arrayCables = Components(
    KilowattHours(4.45E6) + Megajoules(4.45E6),
    Megajoules(8.36E4),
    (Tonnes(1890), Copper),
    (Tonnes(2010), Steel),
    (Tonnes(1280), Lead),
    (Tonnes(345), Polyethylene),
    (Tonnes(212), Polypropylene))

  // Components/UNIT = generic 400 kV substation for 600MW wind farm
  val subStation = Components(
    KilowattHours(6.78E6) + Megajoules(2.71E6),
    Megajoules(9.08E3 + 1.37E4 + 1.66E4),
    (Tonnes(361), Copper),
    (Tonnes(4170 + 1440), Steel),
    (Tonnes(58.7), Insulation),
    (Tonnes(590) * 0.78, LubricatingOil),
    //TODO ? (Tonnes(590)*0.19, WoodPackaging),
    (Tonnes(590) * 0.027, Paint),
    (Tonnes(590) * 0.002, Resin))

  // Components/km
  val externalCables = Components(
    KilowattHours(9.37E4) + Megajoules(6.43E4),
    Megajoules(7.79E4),
    (Tonnes(14.1), Copper),
    (Tonnes(35.2), Steel),
    // TODO (SquareMeters(565),Zinc coating of steel),
    (Tonnes(24.9), Lead),
    (Tonnes(3.25), Polypropylene),
    (Tonnes(5.96), Insulation))

  def embodiedEnergyTransmission(power: Power, distanceToShore: Length) = {
    (arrayCables.embodiedEnergy + subStation.embodiedEnergy) * power.toMegawatts / 600.0 +
      externalCables.embodiedEnergy * distanceToShore.toKilometers
  }

  /**
   * Assessing the Life Cycle Environmental Impacts of Offshore Wind Power Generation and Power Transmission in the North Sea
   *
   * Chirstine Brikeland
   */
  val internalOffshoreCables = new Cable(
    Megawatts(390),
    Components(
      (Kilograms(495142), Lead),
      (Kilograms(387852), Copper),
      (Kilograms(115153), Polyethylene),
      (Kilograms(115153), Steel), // Galvanized
      (Kilograms(115153), Polypropylene)),
    Megajoules(476663), Megajoules(124799), Megajoules(476663), Days(365 * 40))

  // from a wind farm to the grid onshore, quantity = composition / km
  val HVACtoOnshoreGridCables = new Cable(
    Megawatts(390),
    Components(
      (Tonnes(22), Lead),
      (Tonnes(28), Copper),
      (Tonnes(7), Polyethylene),
      (Tonnes(28), Steel),
      (Tonnes(4), Polypropylene)),
    Megajoules(476663), Megajoules(124799), Megajoules(124799), Days(365 * 40))

  val HVDCtoOnshoreGridCables = new Cable(
    Megawatts(1400),
    Components(
      (Tonnes(2 * 22.86), Lead),
      (Tonnes(2 * 13.025), Copper),
      (Tonnes(2 * 5.32), Insulation),
      (Tonnes(2 * 32.89), Steel),
      (Tonnes(2 * 2.93), Polypropylene)),
    Megajoules(476663), Megajoules(124799), Megajoules(124799), Days(365 * 40))

  def transmissionOffshoreEnergy(power: Power, distance: Length) = {
    internalOffshoreCables.embodiedEnergy(power, Kilometers(1)) +
      (if (distance.toKilometers <= 100) HVACtoOnshoreGridCables.embodiedEnergy(power, distance)
      else HVDCtoOnshoreGridCables.embodiedEnergy(power, distance))
  }

  // --- ONSHORE ---
  // Scale this with the size of the wind farm, here it is given for 300 MW
  val refPower = Megawatts(300)

  val transformerStation = Components(
    (Tonnes(91.8), Steel),
    (Tonnes(24), Copper))

  val internalOnshoreCables = Components(
    (Tonnes(63.4), Aluminium),
    (Tonnes(55.2), Plastic),
    (Tonnes(30.9), Copper))

  val externalOnshoreCables = Components(
    (Tonnes(1519), Plastic),
    (Tonnes(953), Aluminium),
    (Tonnes(238.6), Copper))

  def transformerStation(power: Power): Components = transformerStation * (power / refPower)
  def internalOnshoreCables(power: Power): Components = internalOnshoreCables * (power / refPower)
  def externalOnshoreCables(power: Power): Components = externalOnshoreCables * (power / refPower)

}

